layout_spectrum: 0.7637336
typography_spectrum: 0.7865319
color:
  saturation: 0.7668162
  lightness: 0.2298207
  brandStrength: 0.07715049
  rhythmicContrast: 0.6932659
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
name: Asher Sume
